[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["LLLL Colonq <llll@colonq.computer>"]

[workspace.metadata.crane]
name = "teleia"

[profile.dev.package."*"]
opt-level = 2